faif/python-patterns

adapter.py

I think that using keyword arguments instead of passing a dictionary is more pythonic.

edit adapter.py

---

abstract_factory.py
adapter.py

* Remove unused import in adapter.py
* Pep8 check for adapter.py and abstract_factory.py

Remove unused import and pep8 check

---

README.md
lazy_evaluation.py

* add pattern.
* update readme, sorted by alphabet.

Add pattern: lazy_evaluation

---

proxy.py

This modification shows that proxy can be used to block some operations of the other objects. It is a little modification but useful for pattern design.

modified the proxy.py.

---

strategy.py

Last two methods of class StrategyExample where under indented.

Indent error

---

publish_subscribe.py

DRY up the subscribe conditional a bit

---

flyweight.py

Please review my changes. I hope new main will allow to show more hidden details.

Update of flyweight pattern

---

memento.py

* explicit variable names
* some spell-correction
* improved handling of Exceptions using best practices

improved readability as per PEP-8, spell-correction, and some best practices

---

chain.py

Update chain pattern with coroutine realization

---

flyweight.py

I guess current implementation is not clean enough.
Updated implementation will work for python2, for python3 minor updates are required

Updated flyweight with metaclass, made it more generic

---

README.md
registry.py

@faif I have added classification for most important patterns. Check it.

Add classification of patterns. Fix for #70.

---

README.md

Tense was different than all other descriptions and was more confusing

Small grammatical clarification

---

adapter.py

Update for understand the class Adapter

Update for understand the class Adapter

---

3-tier.py

Requesting the Data and Business Logic dependencies in the initializer fits better with the idea of 3-tier.

Adjustment to UI and Business logic for injecting dependencies

---

strategy.py
test_strategy.py

I added a basic unit test for *strategy.py* which verifies the output on the command line output when `python strategy.py` is run in the root directory of python-patterns. Just execute `python -m unittest -v` in the root directory of python-patterns to run the test.

unit test for strategy.py

---

test_command.py

Unit test for MoveFileCommand.execute(). Just run `python test_command.py` or `python -m unittest -v` in the project root directory.

unit test for command.py

---

test_command.py

Refactored and complete (from an acceptance point of view).

add: test undo / change: cls name, setup, teardown

---

chain.py

delete dead hyperlink

---

mvc.py

Decoupled the Controller from the Model and the View. Controllers, models, and views only know about their abstract interfaces. 
Controller now takes a concrete implementation of a model and a view during initialization. Besides the base Model and View classes that guarantee their services, for this example there is a ProductModel and a ConsoleView to serve as their concrete implementations.

Decoupled Model-View-Controller example

---

test_command.py
test_state.py
test_strategy.py

- import of unit test should support python2 and python3 now
- integration test for state.py addedd

change: import of unittest supports python2 and python3

---

test_abstract_factory.py

add: tests for the abstract factory pattern

---

publish_subscribe.py
test_publish_subscribe.py

I added a unsubscribe() method to the Provider class. The integration tests are running with Python 3 on Linux.

Test publish subscribe

---

test_proxy.py

Delay checking added. Tests run on Python 3.4.3 on Linux.

tests for proxy.py

---

test_bridge.py

add: tests for bridge.py

---

delegation_pattern.py

Well ... This is not a pattern from GOF book, but it's a pattern.

Adding delegation pattern

---

facade.py

Remove useless list comprehension

---

test_proxy.py

#138 brought some tests for the actual proxy.py version on my local machine back to my mind. Runs with Python3.4.1 on Linux.

add: test for proxy.py

---

decorator.py

Based on the discussion on #150 I implemented an example of the Decorator design Pattern, based on classes.

Implemented the correct Decorator Pattern (Issue #150)

---

README.md
blackboard.py

- Add Blackboard pattern;
- Update readme, sorted by alphabet.
Resolve issue #154

Add Blackboard pattern -> Resolve issue #154

---

hsm.py

Fixed typo

---

structural/mvc.py
tests/test_adapter.py

Hi!
With no doubt a pattern collection is a great idea to implement and have in hand. Hope my humble corrections would be useful.
On the next stage I hope to:
- Extend test coverage;
- Sieve existing code through PEP8.
Best regards.

Minor improvements

---

tests/test_abstract_factory.py
tests/test_adapter.py
tests/test_borg.py
tests/test_bridge.py
tests/test_command.py
tests/test_flyweight.py
tests/test_hsm.py
tests/test_observer.py
tests/test_proxy.py
tests/test_publish_subscribe.py
tests/test_state.py
tests/test_strategy.py

PEP8 enhancements

---

creational/borg.py
creational/builder.py
creational/factory_method.py
creational/lazy_evaluation.py
creational/pool.py
creational/prototype.py

Minor changes in creational patterns

---

behavioral/catalog.py
behavioral/chain.py
behavioral/chaining_method.py
behavioral/command.py
behavioral/iterator.py
behavioral/mediator.py
behavioral/memento.py
behavioral/observer.py
behavioral/publish_subscribe.py
behavioral/registry.py
behavioral/specification.py
behavioral/state.py
behavioral/strategy.py
behavioral/template.py
behavioral/visitor.py
fundamental/delegation_pattern.py

Similar enhancement in _fundamental_ folder

Minor change in fundamental pattern

---

tests/test_builder.py
tests/test_factory_method.py

Seems like it is time to fix the state of existing code-set by the extension of test coverage.

Test suite extension

---

behavioral/catalog.py
behavioral/chain.py
behavioral/memento.py
behavioral/registry.py
creational/abstract_factory.py
creational/borg.py
creational/factory_method.py
creational/pool.py
creational/prototype.py

Switch to new style class declaration

---

tests/test_facade.py

Code rearranging & coverage expanding

Facade test suite extension

---

dft/constructor_injection.py
tests/test_constructor_injection.py

clean implementation on clean branch

add: constructor injection

---

dft/parameter_injection.py
tests/test_parameter_injection.py

again with clean files from clean branch

add: parameter injection pattern

---

behavioral/catalog.py
dft/constructor_injection.py
dft/setter_injection.py
structural/adapter.py
structural/front_controller.py
tests/test_decorator.py
tests/test_hsm.py
tests/test_prototype.py

* E305 expected 2 blank lines after class or function definition
* E501 line too long (87 > 79 characters)
* W391 blank line at end of file

Fix PEP8 issues

---

creational/factory_method.py

Added a condition checking __main__

---

creational/borg.py

Explanation of the Borg pattern.

#184 - Added description of the Borg pattern.

---

behavioral/catalog.py

just updated my contact information...

updated contact info

---

behavioral/iterator.py

1. remove useless comment
2. use slice syntax

Simplify the code

---

README.md
structural/composite.py

The previous example a little wordy. We can use less code to describe the composite pattern. Less code allows us to focus on the pattern self.

Replace the example of the composite pattern

---

behavioral/chain.py

fix comment

---

creational/builder.py

corrected the spelling of specified

Spelling correction

---

creational/prototype.py

This PR adds an About for the pattern and describes the example below it.

Add description to prototype pattern

---

behavioral/template.py

Fixes #254 
- make some steps optional, as Template pattern suggests
- change base alogrithm from iteration/reverse iteration to smth more like "if this do that, and then do that" thingy
- create concrete templates "by hand" instead of `def make_template` factory
- use one skeleton instead of two

Refactor Template pattern

---

patterns/behavioral/mediator.py
tests/test_outputs.py

Update Mediator pattern

---

.travis.yml
requirements-dev.txt

..forgot to install `codecov` in travis

Install codecov only when needed

---

.gitignore
patterns/structural/proxy.py

Added type hints to proxy pattern and checked with mypy.

Added type hints to proxy pattern

---

patterns/dependency_injection.py

Added type hints to _dependency injection_ pattern and also checked with mypy.

Added type hints to dependency injection pattern

---

patterns/creational/factory.py

Added type hints and checked with mypy

Added type hints to factory pattern

---

patterns/structural/adapter.py

* Added type hints
* Checked with `MyPy`
* Formatted with `Black` formatter

Type checked adapter pattern

---

patterns/structural/composite.py

* Added type hints (checked with mypy)
* Idiomatic interface with `abc.ABC` class
* Formatted with black

Added type hints to composite pattern

---

patterns/behavioral/catalog.py

* Type hints (checked with mypy)
* `.format()` to `f-string`
* Formatted with Black formatter

Added type hints to catalog pattern

---

patterns/behavioral/chain_of_responsibility.py

* Added type hints
* Modern usage of ABC meta while defining abstract base classes
* f-strings instead of `.format()` based string formatting
* Applied black, isort, flake8 formatters

Added type hinting to chain of responsibility pattern

---

patterns/behavioral/observer.py

* Added type hints & checked with mypy
* Updated the `signal` links from Django and Flask documentation
* Introduced `f-string` formatting
* Replaced `Subject.init(self)` with `super().init()`

Added type hints to observer pattern

---

patterns/other/graph_search.py

Added `find_shortest_path_bfs` to GraphSearch class which uses breadth first search with linear time complexity.  
Updated other method names to show that they are depth first search (for example: `find_path` to `find_path_dfs`).
Included an example for the new method.

Implemented breadth first search for shortest graph path in graph_search.py

---

patterns/other/graph_search.py

The recursive function calls were not updated after suffixing the names with dfs.
Also the output in doctest was incorrect.

Used correct function names in recursive calls and fixed the doctest

---

.github/workflows/lint_python.yml
tox.ini

Output: https://github.com/cclauss/python-patterns/actions

GitHub Action to lint Python code

---

tests/behavioral/test_publish_subscribe.py
tests/behavioral/test_strategy.py
tests/structural/test_proxy.py

Removed trailing spaces from function docstrings.
```bash
black --check  .
```
```
All done! ✨ 🍰 ✨
62 files would be left unchanged.
```

:snake: Reformatted with black Closes #375

---

patterns/behavioral/chaining_method.py
patterns/behavioral/iterator_alt.py
patterns/behavioral/observer.py
patterns/behavioral/state.py
patterns/behavioral/strategy.py
patterns/creational/prototype.py
patterns/fundamental/delegation_pattern.py

related to #373
- Added type hint.
- Change string literal to class name according to [PEP-0563#forward-references](https://www.python.org/dev/peps/pep-0563/#forward-references)

Added type hints

---

patterns/creational/factory.py

Finish pull request by emozorov
https://github.com/faif/python-patterns/pull/382

Replace dead link with shortened web archive copy

---

patterns/behavioral/memento.py
patterns/creational/lazy_evaluation.py
patterns/dependency_injection.py
patterns/other/blackboard.py
patterns/other/graph_search.py
patterns/structural/front_controller.py
patterns/structural/mvc.py

Fixed remaining linter issues for fluencydoc's pull request as it was not finished since 23 December
https://github.com/faif/python-patterns/pull/383

Added docstrings to several undocumented functions

---

patterns/creational/factory.py

This PR adds a Protocol to factory pattern, reinforcing the object types.
Resolve #402

Add Protocol to factory pattern

---

.travis.yml
lint.sh
patterns/creational/abstract_factory.py
patterns/other/blackboard.py
patterns/structural/mvc.py
setup.cfg
setup.py
tox.ini

- Moved AbstractExpert to fix a bug
- Added __init__ of AbstractExpert as abstract method
- Replaced future-annotations module with ABC
- Fixed formatting bugs

Abstract factory fixes
