faif/python-patterns

iterator.py

print(number, end=' ') won't work in python 2.x, this patch make it work.
Test passed under python 2.7.9, python 2.6.6 and python 3 (ideone.com used).

add __future__ print_function

---

README.md
registry.py

Such pattern can allow for keeping track of all subclasses for a given parent using `metaclass`.

Implementing registry pattern

---

memento.py

According to the orignal ActiveState recipe, deepcopy() should be called when 'deep' parameter is True.
Relevant orignal snippet: 
```(copy.copy, copy.deepcopy)[bool(deep)](obj.__dict__)```

deepcopy logic inverted

---

builder.py

Summary: Explicitly promise functions implemented by concrete builders by declaring them in the abstract interface.
Reason: Clients should not need to know about extra functionality of concrete builders beyond what is declared in the abstract interface. It is the abstract interface's job to tell clients the interface its concrete implementations will serve.

Explicitly promise functionality in the abstract interface

---

test_observer.py

Tests run with Python 3.4.3 on Linux.

Tests for observer.py

---

proxy.py

Hi!
Accordingly to diagram in wikipedia for proxy pattern: ![proxy pattern](https://upload.wikimedia.org/wikipedia/commons/7/75/Proxy_pattern_diagram.svg)
From interface point of view, proxy method delegate similar functionality to subject. I think, it would be clearer, if example will not call `talk` method on real subject in `work` method in proxy. It would be closer to canonical proxy example.

Modification for proxy example

---

hsm.py
test_hsm.py

I ported the [C++ example of a "hierarchical state machine" (HSM) skeleton](http://www.eventhelix.com/RealtimeMantra/HierarchicalStateMachine.htm#.Vxy9WUL950w) or "nested finite state machine" (NFSM) into Python. I added some unit tests as template. I did not test the production code from an application/acceptance point of view but all unit tests run with Python 3.4.1 on Linux passed. I think this [example could be helpful to a lot of people](https://github.com/thomasquintana/declarative-fsm/issues/5#issuecomment-207853950).

add: hierachical state machine example (state pattern)

---

lazy_evaluation.py

The updated implementation uses a non-data descriptor to achieve the task,
as how it is done in [bottlepy](https://github.com/bottlepy/bottle/blob/cafc15419cbb4a6cb748e6ecdccf92893bb25ce5/bottle.py#L270), [django](https://github.com/django/django/blob/ffd18732f3ee9e6f0374aff9ccf350d85187fac2/django/utils/functional.py#L19), [pyramid](https://github.com/Pylons/pyramid/blob/7909e9503cdfc6f6e84d2c7ace1d3c03ca1d8b73/pyramid/decorator.py#L4) and [pip](https://github.com/pypa/pip/blob/cb75cca785629e15efb46c35903827b3eae13481/pip/utils/__init__.py#L821).
see also: https://gist.github.com/afg984/a2aa7e0ba4e3d908118fa6e4f44f8ac8
which includes a simple comparison & benchmark

lazy evaluation: use descriptors

---

.travis.yml
flyweight.py

Add usage of six library (https://pythonhosted.org/six/#six.add_metaclass) for cross-version compatibility. Add cross-version map handling (in Py 3.x map returns genarator instead of list).
Resolve issue #117 When flyweight.py is run as skript it raises an error

Add six library usage for cross-version compatibility; Resolve issue #117

---

.travis.yml
flyweight.py

Remove usage of third party package (six);
Add with_metaclass function to provide cross-version compatibility without six module dependency.
with_metaclass() is a utility class factory function provided to make it easier to develop code for both Python 2 and 3.
It creates a base class with the specified meta class for you, compatible with the version of Python you are running the code on.
This is needed because the syntax to attach a metaclass changed between Python 2 and 3
Resolve issue #117

Remove third party package dependency

---

tests/test_abstract_factory.py

Hope these changes look pretty and straightforward a bit. But I consider to implement similar operations on all existing tests for clarification purposes only.
In addition a lot of kinky misleadings are there and all they would be elaborated into a contemporary manner. Such as:
`    @classmethod                                                                                                                              
def setUpClass(cls):                                                                                                                      
cls.c = Cat()`
of cause it is just a _setUp_ method of unittest module.
After these clarification manipulation it might be handy to take a closer look on semantic meaning, or what this particular code snippets should illustrate and what …

Existing tests formal purification

---

.travis.yml

Python 3.6.0 is the newest major release of the Python language, and it contains many new features and optimizations. Adding it travis CI configuration.

Add Support for Python 3.6

---

behavioral/command.py
behavioral/observer.py
behavioral/state.py
creational/lazy_evaluation.py
structural/facade.py
tests/test_decorator.py
tests/test_facade.py
tests/test_lazy.py
tests/test_prototype.py
tests/test_state.py

Test suite expanding with _backward compatibility_, of cause.

Prototype and prototype dispatcher test suites

---

creational/prototype.py

A basic performance test:
if __name__ == '__main__':
import time
for _ in range(10):
n = 10000
t0 = time.time()
for i in range(n):
main()
t1 = time.time()
total_n = t1 - t0
print(total_n)
Results:
copy.deepcopy()
0.5343360900878906
0.3827991485595703
0.335590124130249
0.3641550540924072
0.3552978038787842
0.39732789993286133
0.4047999382019043
0.35767602920532227
0.40660595893859863
0.3223540782928467
__class__
0.056986093521118164
0.04783987998962402
0.04845404624938965
0.043087005615234375
0.04816293716430664
0.051603078842163086
0.046478986740112305
0.044046878814697266
0.048792123794555664
0.05028414726257324

Simpler and faster prototype

---

creational/factory_method.py

Disclaimer: I've been looking for a project to start contributing to OSS, and this one seemed interesting and not too complicated. Since I'm a newbie in all this, any advice and suggestions are welcome! Thanks!
I intend to work on the issue "Short descriptions #184" (https://github.com/faif/python-patterns/issues/184), and the first step was to include some explanation about the Factory Method pattern.
If possible, I would like some feedback on the description I added so I can have a better idea on what to do with the others.

Explanation of the Factory Method pattern

---

structural/flyweight.py

if the class has its own `__bool__` method, `not instance` may equal True.

fix a minor bug

---

creational/abstract_factory.py
creational/builder.py
creational/pool.py

As per issue #184 this adds some short descriptions (following the established style) to some of the patterns of the class.
(I may do some more later)

Add short descriptions to Abstract Factory, Builder and ObjectPool

---

creational/abstract_factory.py
tests/test_abstract_factory.py

Once we appreciate that:
1) classes are their own factories and
2) classes are first class objects in Python,
this pattern is massively simpler in idiomatic Python.  Additional factory
classes are not needed.
This change also removes the `get_food` method because:
1) This violates the single responsibility principle of the factory
2) It obscures the main point.
If we want an association between animals and what food they eat we should either:
1) make it part of the Pet interface
2) or, have another callable which can make this decision
(presumably it should be passed the animal instance in order to do so).
Or, if we really need it, create an interface that does both creation and
feeding as before, but to have that in the this pattern obscures the
simplicity of how this can and should be …

Simplified the Abstract Factory Pattern to be Pythonic

---

creational/builder.py
tests/test_builder.py

This follows the motto "a class with only one method that actually does anything should be a function", with the result that using the director function requires one line of code instead of 5.

Made builder pattern much simpler by removing unnecessary class.

---

other/graph_search.py

`path` will get modified in recursive call if passed by reference. And can be simply fixed by passing a copy of it.

fix graph search find path backtracking

---

creational/builder.py
tests/test_builder.py

This builds on #216 as per the comments there.

Further simplifications to builder pattern

---

structural/adapter.py

Passing a dict instead of kwarg.
Initialising Dog class.

Fix adapter usage example

---

behavioral/chain.py

This PR adds a description and a TL;DR to the chain pattern.

Add description to chain pattern

---

behavioral/strategy.py

I've added the description to the strategy pattern.

Add description to the strategy pattern

---

.coveragerc

This will exlcude lines like the following from codecov report:
https://codecov.io/gh/faif/python-patterns/src/master/structural/mvc.py#L12

Add coveragerc to ignore NotImplementedError's in tests

---

fundamental/delegation_pattern.py

The current code does not allow the delegator to return the value of properties of the delegate but can only call its methods. Moreover if the method does not exist then `None` is returned rather than raising an exception.
This PR is for fixing the above.

Allow delegator to return delegate's properties

---

structural/mvc.py

This PR contains:
* Fix #247: simplify `__str__` method in `structural/mvc.py`

Simplify __str__ in structural/mvc.py

---

behavioral/chain.py

Fixes #252 
- aiming for simplification this PR removes second implementation with coroutines, client with delegation method and timing
- rename `_successor` attribute to `successor`: pattern should provide method to add/change successor dynamicly (usually is called "set_next"). Additional setter would be overkill, but leading underscore discourages changes (wrongly).
- bugfix: add check in handler method if there is a successor (otherwise we do not handle end-of-chain properly)
- add docstring to base `def handle(self, request)`
- rename `_handle` to `compare`
- change intervals from `0 < request <= 10` to `0 <= request < 10: zero-indexing is more natural in such cases (and handles zeroes)
- change numbers in concreate handle names. This way it is easier to understand output e.g. when …

Refactor chain pattern

---

.travis.yml

1. `coveralls` and `codecov` do basically the same
2. here is travis output for several (possibly all) latest PRs
```
$ coveralls
Submitting coverage to coveralls.io...
Coverage submitted!
Couldn't find a repository matching this job.
Traceback (most recent call last):
File "/home/travis/virtualenv/python3.6.3/bin/coveralls", line 11, in <module>
sys.exit(main())
File "/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/coveralls/cli.py", line 80, in main
log.info(result['url'])
KeyError: 'url'
```

Remove coveralls

---

.travis.yml
requirements-dev.txt

fixes #259 
**Split doctests from unittests**
Different types of tests belong to different CI stages.
Also, in this particular repository doctests can also be tests for script OUTPUTS (I will make a separate PR to show what I mean).
**Separate `requirements-dev.txt`**
It is very convenient (for local development) to be able to setup deps and pre-commit hooks.
In case of travis-ci packages already present in container (e.g. pytest) will be skipped.
As for `flake8` and linting - I plan to address that in separate PR.

Move from nosetests to pytest

---

behavioral/strategy.py
tests/test_strategy.py

- I dont think we should use `types.MethodType(func, self)` on a day to day basis.
- I also wanted to see something more specific than "StrategyExample", "execute", "execute_replacement1/2"..

Refactor Strategy

---

.travis.yml
requirements-dev.txt

Default travis env is Ubuntu Trusty 14.04 which doesn't have 3.7
I propose to 
- move from Trusty to Xenial (16.04)
- add support for 3.7
- drop support for 3.4, 3.5
https://docs.travis-ci.com/user/reference/xenial/#python-support

Travis config: test with 3.7, drop 3.4, 3.5

---

patterns/behavioral/catalog.py
patterns/behavioral/chain.py
patterns/behavioral/chaining_method.py
patterns/behavioral/command.py
patterns/behavioral/iterator.py
patterns/behavioral/mediator.py
patterns/behavioral/memento.py
patterns/behavioral/observer.py
patterns/behavioral/publish_subscribe.py
patterns/behavioral/specification.py
patterns/behavioral/state.py
patterns/behavioral/template.py
tests/test_outputs.py

according to plans in #258 
- updated structure for most of behavioral patterns
- added them to `test_outputs.py`
Found a couple of interesting things related to output. will investigate and fix separately

Add main function and tests for output for most of behavioral patterns

---

patterns/behavioral/memento.py
patterns/behavioral/template.py
patterns/structural/adapter.py
tests/test_outputs.py

This PR is for discussion purposes but it contains changes which are ready to merge.
Please review from easiest to longest: Template, Adapter, Memento
**Template**: not much changed (I expect it to be the common case for other examples)
**Adapter**: I don't know why the diff is like that, it shows many functions I didn't touch. My advice for this particular commit is to compare before/after files by eye.
Because the important change is in one line:
before
```python
print(objects[0].__dict__)
{'make_noise': <bound method Dog.bark of <__main__.Dog object at 0x7f631ba3fb00>>, 'obj': <__main__.Dog object at 0x7f631ba3fb00>}    # noqa flake8
```
after
```python
>>> objects[0].__dict__['obj'], objects[0].__dict__['make_noise']
(<...Dog object at 0x...>, <bound method Dog.bark of <...Dog object …
```

Doctests all around

---

patterns/structural/flyweight__py3.py
patterns/structural/flyweight_with_metaclass__py3.py

Current example of Flyweight has actually two of them: with overriding `__new__` and with metaclass.
I found the one with metaclass especially hard to follow and decided to split-up the examples.
What this PR does:
- move metaclass example to a separate file
- move from printing outputs to doctest style
- add a bunch of comments and a link to Brandon Rhodes blog post about flyweights

Update flyweight pattern

---

README.md

Remove suffix to fix broken links to files

---

patterns/other/blackboard.py
requirements-dev.txt
tox.ini

This PR was intended to add doctest for `blackboard.py`.
As a workaround for `random` outputs - `random.seed` was used.
- `random.seed(1234)` if you should run script by hand like `python patterns/other/blackboard.py`
- `pytest-randomly` plugin to run via `pytest`
I've added related comments to `tox.ini` but need to explain a bit futher: 
For unittest part - plugin is disabled not because of `random.*` outputs, but because plugin shuffles order of tests and it has found another issue (some tests depend on their order). I haven't investigated it further for the moment, will do it a bit later.
Please let me know if someone has simpler way of testing with `random.*` or sees problems with current approach.
p.s. there is another script with use of random - `abstract_factory`. And so I can fix …

Use random.seed for deterministic doctest outputs

---

patterns/creational/pool.py

Fix simple typo:  insided -> inside

---

patterns/creational/prototype.py

change "as it make.." to "as it makes.."

Fix prototype.py typo

---

README.md
patterns/behavioral/iterator_alt.py

In this PR I add the alternative version on how to implement the Iterator pattern using the Iterator protocol from Python. I followed the same example in the original version so that they can be easily compared.

Added alternative implementation for Iterator pattern using the Iterator protocol

---

append_output.sh
patterns/structural/proxy.py

add a little more description and references

enhance top description

---

patterns/behavioral/command.py

changing description and example to add more clarification

---

patterns/fundamental/delegation_pattern.py

**Delegation** pattern can be much easier to understand with **type annotations**. It doesn't affect the tests. Tested on python 3.6, 3,7 and 3.8. I also suggest adding type hints gradually to other examples too. This can make the intents of the code snippets much clearer.  
Also fixed some minor formatting issues (Adding 2 empty lines after import, double quoting the strings everywhere etc.)

Added type hints to delegation pattern

---

patterns/structural/3-tier.py

* Added type hints with proper generic types
* Converted `.format` based string formatting to `f-string` based formatting to avoid `mypy` string interpolation error
* Fully type-checked with `mypy`
* Formatted with `black` formatter with default config

Added type hints to 3-tier structural pattern

---

patterns/structural/mvc.py

Defining interfaces in the following manner isn't very Pythonic:
```python
class Interface:
def method(self):
raise NotImplementedError
```
Because this will still let you initialize the interface. The above example will only raise an error when you try to access the `method` which goes against the very definition of interfaces. You shouldn't be able to initialize an interface at all and it should fail early when you try to do so without subclassing. Python doc recommends using the `abc` module to define interfaces in the following manner:
```python
from abc import ABC, abstractmethod
class Interface(ABC):
@abstractmethod
def method(self):
pass
```
This will fail the moment you try to initialize the interface without subclassing. Changed that.

ABC based interface in mvc pattern

---

.gitignore
patterns/creational/borg.py

The Borg pattern should not change state on new instance creation unless explicitly changed. Currently all new instances change the state to `Init`. 
Update the pattern to reflect how it should behave. The Borg class should be subclassed and used. State should only change if explicitly changed.
Updated the docstring slightly to reflect the update. 
- https://learning.oreilly.com/library/view/python-cookbook/0596001673/ch05s23.html
- http://www.aleax.it/5ep.html
- #3

Update borg pattern to reflect discussion in issue#3

---

.travis.yml
tox.ini

As defined in the tox documentation
(https://tox.readthedocs.io/en/latest/config.html#tox-environments),
environment with names "pyNM" have special meaning and implicitly define
the Python interpreter.
Environment names ci37 and ci38 don't have any special meaning and run
the default version of the interpreter. This results in that that both
environments use the same interpreter locally.
The PR changes the names of environments to make sure that tox creates a
virtual environment with the correct interpreter version.

Update tox.ini to use py37,py38 instead of ci37,ci38

---

patterns/other/graph_search.py

Added a base case for BFS like DFS.
No need to use break in loop. Create the path and return it.
Changed the docstests to remove some ambiguity in variable names ( graph vs graph1) and added some more to cover the edge cases.

Added base case and return the path as soon as end node is visited

---

patterns/behavioral/publish_subscribe.py
patterns/structural/front_controller.py

___codespell --quiet-level=2___
```
./python-patterns/patterns/behavioral/publish_subscribe.py:68: subscirbed ==> subscribed
./python-patterns/patterns/structural/front_controller.py:30: cant ==> can't
./python-patterns/patterns/structural/front_controller.py:72: cant ==> can't
```

Fix typo discovered by codespell

---

.github/workflows/lint_python.yml

Make codespell and isort mandatory tests.
Drop bandit whose test results are not enlightening.

Make codespell and isort mandatory tests

---

.github/workflows/lint_python.yml
patterns/behavioral/iterator.py
patterns/behavioral/memento.py
patterns/behavioral/publish_subscribe.py
patterns/behavioral/template.py
patterns/creational/abstract_factory.py
patterns/dependency_injection.py
patterns/structural/bridge.py
patterns/structural/decorator.py
patterns/structural/facade.py
patterns/structural/flyweight.py
patterns/structural/mvc.py
tests/creational/test_lazy.py
tests/creational/test_pool.py
tests/test_hsm.py

https://github.com/asottile/pyupgrade plus blacken two test files and add mypy in allow_failures mode.

pyupgrade --py36-plus **/*.py

---

patterns/creational/abstract_factory.py
tests/creational/test_abstract_factory.py

After reading #366, I think it is not necessary to add more types of things but it can be more clear.
2 Points.
1.
I think **abstract factory can offer a concrete factory which can provide some different things from input/choice**.
Then how about change show_pet() into something which can accept args like `name`?
2.
abstract factory should have `abstract_factory`, `concrete_factory` and `products`.
And in former abstract_factory.py
```
abstract_factory: Class<PetShop>
concrete_factory: Class<Dog/Cat>
products: Pet Object?, string? or also output like print("woof")?
```
products is not clear.
So I returned Pet Object to make more clear what product is.

Update abstract_factory more elaborate

---

.gitignore
.travis.yml
Makefile
patterns/behavioral/iterator.py
requirements-dev.txt
setup.cfg
setup.py
tox.ini

Several small updates
- add .coverage to .gitignore. it is created when I run `tox`
- update minimum testing version to 3.8 (#369)
- refactor iterator.py for https://www.flake8rules.com/rules/E731.html
- update Makefile
- comment out pip-tools part: which seems not to be used ever
- exclude .tox from linting
- Update requirements-dev.txt
- Add black and isort: this has been originally in Makefile.
-  update versions
- integrate .venv and venv into venv
In addition, I think it is helpful for contributors if there is info of below.
From root files, I found the way to start developing this repo is
```
git clone git@github.com:faif/python-patterns.git
cd python-patterns
python -m venv venv
pip install --upgrade pip
make pyupgrade
```
And after coding, check it by this.
```
make pylinter
tox …
```

house keeping update

---

patterns/behavioral/strategy.py
patterns/structural/3-tier.py
patterns/structural/front_controller.py
tests/behavioral/test_strategy.py

Added type hints and pytest tests

---

patterns/creational/prototype.py

I have used class name with quotes as return type because we can not use class name before its definition.
1 file changed `.\patterns\creational\prototype.py`
```diff
@@ -29,7 +29,7 @@ def __init__(self, value: str = "default", **attrs: Any) -> None:
self.value = value
self.__dict__.update(attrs)
-   def clone(self, **attrs: Any) -> None:
+   def clone(self, **attrs: Any) -> "Prototype":
"""Clone a prototype and update inner attributes dictionary"""
```

Closes #377: No return value expeced :bug:

---

patterns/creational/factory.py

Fixes #380 by using web archive link.
Unfortunately, it violates PEP-8 a bit by being longer than 80 characters, but I couldn't find a way to shorten the link further.

Replaces dead link with web archive copy

---

patterns/behavioral/catalog.py
patterns/behavioral/chain_of_responsibility.py
patterns/behavioral/command.py
patterns/behavioral/memento.py
patterns/behavioral/registry.py
patterns/behavioral/specification.py
patterns/creational/borg.py
patterns/structural/flyweight.py
setup.cfg

re #373
You can check all problems are fixed by running `mypy .`
I added small config for mypy.

fix(typing): all problems by mypy

---

patterns/creational/borg.py

There is a small typo in patterns/creational/borg.py.
Should read `assigning` rather than `assigining`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, assigining -> assigning

---

patterns/creational/abstract_factory.py

Added a PetShop instance so that `random.seed` actually has an effect. Fixes #376 (the issue has been open for an year)

fix: created PetShop instance

---

patterns/behavioral/publish_subscribe.py
patterns/behavioral/state.py
patterns/creational/borg.py
patterns/creational/builder.py
patterns/fundamental/delegation_pattern.py
patterns/other/blackboard.py
patterns/structural/decorator.py
patterns/structural/facade.py
patterns/structural/front_controller.py

Add type hints to multiple design pattern examples
Related to https://github.com/faif/python-patterns/issues/373

Add more type hints

---

patterns/behavioral/chaining_method.py

It makes more sense to pass the `move` object to the `do_action()` method instead of having to initialize a `Person` instance with an `Action` object.
In other words, this:
`person.do_action(move).amount('5m').stop()`
Is better than:
`person.do_action().amount('5m').stop()`

Pass the `move` object to the `do_action()` method

---

.github/workflows/lint_python.yml
.gitignore
README.md
lint.sh
patterns/behavioral/catalog.py
patterns/behavioral/iterator_alt.py
patterns/behavioral/memento.py
patterns/behavioral/publish_subscribe.py
patterns/behavioral/strategy.py
patterns/creational/abstract_factory.py
patterns/creational/borg.py
patterns/creational/factory.py
patterns/creational/prototype.py
patterns/other/blackboard.py
patterns/other/graph_search.py
tests/behavioral/test_strategy.py
tests/creational/test_pool.py

A collection of small changes to comply with lining rules.
Also added folders - dist and build to the .gitignore.  These are generated in the CI pipeline. adding to gitignore prevents a user from accidentally committing these whilst working through pipeline.

#415 linter preventing prs

---

patterns/structural/mvc.py

The MVC-pattern was missing routing for using multiple controllers, models and views.
With this addition, it is now possible to view different data from multiple models from the CLI.
This concept is also known within ASP.net: https://dotnettutorials.net/lesson/asp-dot-net-mvc-routing/

Added routing

---

.codespellignore
lint.sh
patterns/structural/mvc.py
tox.ini

Cleaned up lint.sh:
- Removed first execution of Black because Black is already executed by isort.
- Specifically directed all the linting tools to the specific location of ./patterns. By not doing so, users will experience much more noise from the linting tools when directories like venv/ and .tox/ and setup.py located in the root are being linted.
- Moved all installs of packages on top of the file, so that the rest of the output is not getting trashed by it.

Lint sh cleanup

---

patterns/fundamental/delegation_pattern.py

- It's required to capture the args/kwargs when called at run time.
- Fix doctest output to include hints
Addresses: #431

Highlight the need for a wrapper in delegate

---

.travis.yml
lint.sh
patterns/structural/mvc.py
setup.cfg
setup.py
tox.ini

Added types and extra comments to the pattern

Mvc add typing

---

patterns/behavioral/servant.py
tests/behavioral/test_servant.py

This pull request implements the [Servant](https://en.wikipedia.org/wiki/Servant_(design_pattern)) behavioral design pattern.
After doing some research about [design patterns](https://en.wikipedia.org/wiki/Software_design_pattern), I found out that this pattern was missing.

Servant pattern

---

patterns/behavioral/catalog.py

This PR fixes minor typos in the top-level docstring of patterns/behavoural/catalog.py
Changes
Corrected "depending of" -> "depending on"
Changed "static function" -> "static functions"
Why
Improves readability and correctness of documentation

fix(docs): correct typos in top comment of catalog.py
